// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyyfvcqizizzteztgjsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5eWZ2Y3Fpeml6enRlenRnanNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzE3OTAsImV4cCI6MjA1OTgwNzc5MH0.JlX5cXD21imZX4uv8l_8JIvdU9bG9BHm_HmPzwXH_II";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);